### PR TITLE
Xamarin Static Bindings

### LINKED ISSUE #12: Static binding for XAML (UWP)

### PR DESCRIPTION
**Pull request by enisn**
Closes #12 

---

### Xamarin Static Binding
You can use static values instead of binding texts. It's more effective and has better performance.

- Install `I18NPortable.Xamarin` extension to your Xamarin Forms Project.

- Go your XAML page and add following xml namespace:
```xml
xmlns:i18n="clr-namespace:I18NPortable.Xamarin.Xaml.Extensions;assembly=I18NPortable.Xamarin"
```

- Then use it with calling `i18n:Translate`

```xml
<Label Text="{i18n:Translate HelloWorld}" />
```

Entire page sample:
```xml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:d="http://xamarin.com/schemas/2014/forms/design"
             xmlns:i18n="clr-namespace:I18NPortable.Xamarin.Xaml.Extensions;assembly=I18NPortable.Xamarin"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             mc:Ignorable="d"
             x:Class="Sample.MainContentPage">
    <ContentPage.Content>
       <StackLayout>
            <Label Text="{i18n:Translate HelloWorld}"
                VerticalOptions="CenterAndExpand" 
                HorizontalOptions="CenterAndExpand" />
        </StackLayout>
    </ContentPage.Content>
</ContentPage>
```

### CODE REVIEW

**Comment by enisn** [comment]
Hi @xleon ,

Any idea on this logic?

**Comment by xleon** [comment]
Hi @enisn 
Thanks for the effort. It looks good so far. 
I will do a couple of tests myself as soon as I can in order to complete the merge.

**Comment by SeriousM** [comment]
Hi! Any updates on this? The binding extension would be very nice to have 😄

**Comment by enisn** [comment]
Any updates about that logic?

**Pull request closed without merging**
